<!DOCTYPE html>
<html>
<head>
    <meta name = "viewport" content = "width=device-width, initial-scale=1">
    <meta http-equiv = "Content-Type" content = "text/html; charset=utf-8" />
    <title>Emanoogle</title>

    <link href = "css/reset.css" rel = "stylesheet" type = "text/css" />
    <link href = "css/style.css" rel = "stylesheet" type = "text/css" />

    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/hideFile.js"></script>
    <script type="text/javascript" src="js/functions.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head>
<body>
<div id="Upper_Menu">
    <section class="logo">
        <header>
            <nav>
                <ul>
                    <li><a href = "index.php">Search</a></li>
                    <li><a href = "add.php">Upload</a></li>
                    <li><a href = "remove.php">Delete</a></li>
                </ul>
            </nav>
        </header>
    </section>
</div>
